server:
    port: 80
    servlet:
     context-path: /
auth-server: http://localhost:8081
security:
  oauth2:
    client:
      client-id: testclient
      client-secret: testclient
      scope: test
      access-token-uri: ${auth-server}/auth/oauth/token
      user-authorization-uri: ${auth-server}/auth/oauth/authorize
    resource:
      jwt:
        key-value: 123
      token-type: JWT
#    resource:
#      token-info-uri: ${auth-server}/auth/oauth/check_token

spring:
  redis:
    host: 47.95.220.97
    port: 6379
    password: 123456
logging:
  level:
    root: debug
jwt:
   header: token
   tokenHead: Bearer